/** Generated by the screenshot pipeline: natural pixel size of each published gallery image. */
export const galleryDims: Record<string, [number, number]> = {
  "/projects/medmar/overview-departments.webp": [
    1440,
    900
  ],
  "/projects/medmar/asset-detail.webp": [
    1440,
    900
  ],
  "/projects/medmar/eam-analytics.webp": [
    1440,
    900
  ],
  "/projects/medmar/pm-panel.webp": [
    1440,
    900
  ],
  "/projects/medmar/pm-overdue.webp": [
    1440,
    900
  ],
  "/projects/medmar/fault-repair-jobs.webp": [
    1440,
    900
  ],
  "/projects/medmar/fault-analytics.webp": [
    1440,
    900
  ],
  "/projects/medmar/production-dashboard.webp": [
    1440,
    900
  ],
  "/projects/medmar/weekly-plan.webp": [
    1440,
    900
  ],
  "/projects/medmar/warehouse-dashboard.webp": [
    1440,
    900
  ],
  "/projects/medmar/material-request.webp": [
    1440,
    900
  ],
  "/projects/medmar/notifications.webp": [
    1440,
    900
  ],
  "/projects/medmar/qc-dashboard.webp": [
    1440,
    900
  ],
  "/projects/medmar/qc-daily-form.webp": [
    1440,
    900
  ],
  "/projects/medmar/qc-form-settings.webp": [
    1440,
    900
  ],
  "/projects/medmar/qc-shift-signoff.webp": [
    1440,
    900
  ],
  "/projects/medmar/m-departments.webp": [
    440,
    956
  ],
  "/projects/medmar/m-asset-tree.webp": [
    440,
    956
  ],
  "/projects/medmar/m-pm.webp": [
    440,
    956
  ],
  "/projects/medmar/m-fault-jobs.webp": [
    440,
    956
  ],
  "/projects/medmar/m-production.webp": [
    440,
    956
  ],
  "/projects/medmar/m-qc-form.webp": [
    440,
    956
  ],
  "/projects/medmar/m-qc-dashboard.webp": [
    440,
    956
  ],
  "/projects/medmar/m-material-request.webp": [
    440,
    956
  ],
  "/projects/medmar/m-warehouse.webp": [
    440,
    956
  ],
  "/projects/medmar/cost-report.webp": [
    1440,
    430
  ],
  "/projects/medmar/m-notifications.webp": [
    440,
    956
  ],
  "/projects/salti/home-hero.webp": [
    1440,
    900
  ],
  "/projects/salti/home-ar.webp": [
    1440,
    900
  ],
  "/projects/salti/products-menu.webp": [
    1440,
    460
  ],
  "/projects/salti/products.webp": [
    1440,
    900
  ],
  "/projects/salti/products-ru.webp": [
    1440,
    900
  ],
  "/projects/salti/food.webp": [
    1440,
    900
  ],
  "/projects/salti/food-grid.webp": [
    1440,
    900
  ],
  "/projects/salti/food-modal.webp": [
    1440,
    900
  ],
  "/projects/salti/food-dark.webp": [
    1440,
    900
  ],
  "/projects/salti/medical.webp": [
    1440,
    900
  ],
  "/projects/salti/industrial.webp": [
    1440,
    900
  ],
  "/projects/salti/tablet.webp": [
    1440,
    900
  ],
  "/projects/salti/catalog-page3.webp": [
    1440,
    900
  ],
  "/projects/salti/about.webp": [
    1440,
    900
  ],
  "/projects/salti/contact.webp": [
    1440,
    800
  ],
  "/projects/salti/full-home.webp": [
    1280,
    6876
  ],
  "/projects/salti/full-about.webp": [
    1280,
    5415
  ],
  "/projects/salti/full-catalog.webp": [
    1280,
    1918
  ],
  "/projects/salti/full-products.webp": [
    1280,
    1832
  ],
  "/projects/salti/full-food.webp": [
    1280,
    4140
  ],
  "/projects/salti/full-medical.webp": [
    1280,
    1720
  ],
  "/projects/salti/full-survey.webp": [
    1280,
    2708
  ],
  "/projects/salti/m-home-tr.webp": [
    780,
    1688
  ],
  "/projects/salti/m-home-en.webp": [
    780,
    1688
  ],
  "/projects/salti/m-home-ar.webp": [
    780,
    1688
  ],
  "/projects/salti/m-home-dark.webp": [
    780,
    1688
  ],
  "/projects/salti/m-menu.webp": [
    780,
    1688
  ],
  "/projects/salti/m-products-tr.webp": [
    780,
    1688
  ],
  "/projects/salti/m-products-ar.webp": [
    780,
    1688
  ],
  "/projects/salti/m-products-ru.webp": [
    780,
    1688
  ],
  "/projects/salti/m-food.webp": [
    780,
    1688
  ],
  "/projects/salti/m-food-dark.webp": [
    780,
    1688
  ],
  "/projects/salti/m-food-grid.webp": [
    780,
    1688
  ],
  "/projects/salti/m-food-modal.webp": [
    780,
    1688
  ],
  "/projects/salti/m-industrial.webp": [
    780,
    1688
  ],
  "/projects/salti/m-tablet.webp": [
    780,
    1688
  ],
  "/projects/salti/m-catalog.webp": [
    780,
    1688
  ],
  "/projects/salti/m-catalog-page3.webp": [
    780,
    1688
  ],
  "/projects/salti/m-about.webp": [
    780,
    1688
  ],
  "/projects/salti/m-blog.webp": [
    780,
    1688
  ],
  "/projects/salti/m-survey.webp": [
    780,
    1688
  ],
  "/projects/salti/m-contact.webp": [
    780,
    1120
  ],
  "/projects/salti/m-full-products.webp": [
    780,
    8213
  ],
  "/projects/salti/m-full-industrial.webp": [
    780,
    4633
  ],
  "/projects/salti/m-full-medical.webp": [
    780,
    4775
  ]
};
